INSERT INTO region VALUES (1,'America del Sur');
INSERT INTO region VALUES (2,'America Central');
INSERT INTO region VALUES (3,'America del Norte');
INSERT INTO pais VALUES (1,'Peru',1);
INSERT INTO pais VALUES (2,'Chile',1);
INSERT INTO pais VALUES (3,'Argentina',1);
INSERT INTO pais VALUES (4,'Bolivia',1);
INSERT INTO pais VALUES (5,'Brazil',1);
INSERT INTO pais VALUES (6,'Paraguay',1);
INSERT INTO pais VALUES (7,'Ecuador',1);
INSERT INTO pais VALUES (8,'Colombia',1);
INSERT INTO pais VALUES (9,'Argentina',1);
INSERT INTO pais VALUES (10,'Venezuela',1);
INSERT INTO pais VALUES (11,'Panama',2);
INSERT INTO pais VALUES (12,'Costa Rica',2);
INSERT INTO pais VALUES (13,'Nicaragua',2);
INSERT INTO pais VALUES (14,'Honduras',2);
INSERT INTO pais VALUES (15,'El Salvador',2);
INSERT INTO pais VALUES (16,'Guatemala',2);
INSERT INTO pais VALUES (17,'Mexico',3);
INSERT INTO pais VALUES (18,'Canada',3);
INSERT INTO pais VALUES (19,'EE.UU',3);
INSERT INTO servers VALUES (1,'EE.UU Este',16);
INSERT INTO servers VALUES (2,'EE.UU Norte',16);
INSERT INTO servers VALUES (3,'Brazil',5);
INSERT INTO servers VALUES (4,'Peru',1);
INSERT INTO servers VALUES (5,'Chile',2);
INSERT INTO videojuego VALUES (1,1,'Dota 2', 'MOBA');
INSERT INTO videojuego VALUES (2,0,'LeagueofLegends', 'MOBA');
INSERT INTO videojuego VALUES (3,2,'Counter-Strike:GlobalOffensive', 'Shooter');
INSERT INTO videojuego VALUES (4,3,'Fornite', 'Shooter');
INSERT INTO videojuego VALUES (5,4,'HearthStone', 'Juego de Cartas');
INSERT INTO administrador VALUES (2,'Diego','diego@hotmail.com','diego123');
INSERT INTO administrador VALUES (1,'Edward', 'edward@hotmail.com','edward123');

insert into usuario values (1,'1234','juan32@hotmail.com','activo','12/01/2003','god','masterX','120',1);
insert into torneo values(1,'1vs1',30,'aceptado','en curso','14/03/2006','pc','1500$','Dota finals',5,2,1);
insert into inscripciontorneo values(1,'11/02/2003',1,1);